### ISSUE TITLE
Thank you so much for your article! How to arrange the data? How do I set up data storage?

### ISSUE THREAD

**Issue by liubaoning111** [HealthX-Lab/MedCLIP-SAM#1]

**Comment by TahaKoleilat** [comment]
Hi @liubaoning111,

Thank you for your interest in MedCLIP-SAM!

To arrange your data, it's very simple. You should first keep all images in one directory, then follow step 1 to generate saliency maps by indicating the name of the directoy using `--image-folder <path/to/data/dir>` and an indicate the output directory using `--save-folder <path/to/save/dir>`. For steps 2 and 3, the pattern is the same. You will have to use the output of step 1 as the input to step 2 and so on. You can follow in detail the steps in the [README](https://github.com/HealthX-Lab/MedCLIP-SAM/blob/main/README.md).

Let me know if you have any other questions.

**Comment by liubaoning111** [comment]
Thank you very much for your help! I would also like to ask if our model can only achieve single-object segmentation? What if it's multi-target segmentation?

**Comment by TahaKoleilat** [comment]
The overall framework can segment multiple objects of the same class like chest lungs. However, for multi-class semantic segmentation, while SAM can technically segment multiple instances of various classes in an image, we recommend to generate saliency maps for each class seperately. So, if you have multiple classes in one image, you can generate saliency maps for each target seperately using a suitable text prompt and then segment using SAM.

**Comment by liubaoning111** [comment]
thank you for your answer!It helps me a lot!I have successfully completed the resoning part!  Is there code that can be trained to help private data sets fine-tune the model further?

**Comment by TahaKoleilat** [comment]
We are currently working on this and will make the code availabe soon.

**Comment by TahaKoleilat** [comment]
Hi @liubaoning111

I'm closing this issue for now. Please feel free to reopen it if you have any further questions.

Thank you!

**Comment by cht619** [comment]
what text clip is suitable for Breast Tumor Ultrasound dataset?

**Comment by liubaoning111** [comment]
Thank you very much for your article. I did not find that you uploaded the training code, how is the preparation? I'm really looking forward to it!
